### ISSUE TITLE
Details - Box Fixed Height 260px

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#12]
The Details DIV Should be Fixed Height so that the Map Does NOT Change Position when Different Attractions are selected 

CSS Design will be enhanced in Future Milestones  

![detailsdiv](https://cloud.githubusercontent.com/assets/887805/8997615/72c40294-36f1-11e5-9824-0f74639fbe93.png)

**Comment by xibbit** [comment]
When I set details div height to 260px the image moves slightly out of div.
![screen shot 2015-07-31 at 6 04 12 pm](https://cloud.githubusercontent.com/assets/674794/9007288/8c78be2a-37ad-11e5-8cc7-0de43e7d8b16.png)

**Comment by stuartshay** [comment]
Can you make the div larger then maybe 270px what ever works best you can change it too

Stuart
