### ISSUE TITLE
Over Lay - On/Off Bug

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#13]
The On/Off Overlay does not Function Correctly 

![overlay](https://cloud.githubusercontent.com/assets/887805/8998035/83740b7a-36f6-11e5-91aa-03ac3cbaf8b5.PNG)

**Comment by xibbit** [comment]
Did this work?

**Comment by stuartshay** [comment]
Gaurav:

Sorry for the delay, I wanted to stabilize the code before starting new work, i did not want to deal with broken code and the issues with it,  If you are available we can start a new Milestone.

I changed the functionality, which should function better. Right now there is only 1 overlay this is for the Greenwood Map, When the map is loaded check if overlays exists for the map (There can be multiple overlays in the future)

http://api.navigatorglass.com/swagger/ui/index#!/Maps/Maps_GetFeatues

If a overlay exists display the drop down and by default set the overlay to off. 

I can clarify if there are questions
