### ISSUE TITLE
Zoom-to-Fit All Markers on Google Map v3 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#17]
Zoom-to-Fit All Markers on Google Map v3 

Map Should Scale so all points on the map are displayed. 
Zoom Should be Min Allowed 

http://viklund.fi/2014/10/zoom-to-fit-all-markers-on-google-maps/
http://salman-w.blogspot.com/2011/03/zoom-to-fit-all-markers-on-google-map.html

Current Page Load
![current](https://cloud.githubusercontent.com/assets/887805/9485356/4d5b5b84-4b86-11e5-9ef0-f34fb01127c8.png)

All Points are displayed.
Zoom is Min where everything fits
![future](https://cloud.githubusercontent.com/assets/887805/9485403/a8400dd8-4b86-11e5-9421-c7be3d487a7b.png)

**Comment by xibbit** [comment]
![screen shot 2015-08-26 at 3 55 20 pm](https://cloud.githubusercontent.com/assets/674794/9491003/8cc19a9e-4c09-11e5-9376-ee11f18cd3e2.png)
