### ISSUE TITLE
Grunt Config - Bug 

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#31]
1) Docker ENV Variable not working 

API Port Not Set 

```
# Set environment variables
ENV PORT="3000"
ENV NODE_ENV="Dev"
```
![port](https://cloud.githubusercontent.com/assets/887805/19914597/43001cf4-a082-11e6-9376-60a4c52252f7.PNG)

**Comment by stuartshay** [comment]
I run ````grunt serve:stage````

API Setting does not work

http://navigatormaps_api/api  - (THIS is Needed for DOCKER URL) 

Page is calling prod API

**Comment by leduong** [comment]
HI!

Need set environment first, default vaule Local

```bash
grunt serve
```

**Comment by leduong** [comment]
Hi

navigatormaps_api is localhost, can't map to internet. only use with proxy

**Comment by stuartshay** [comment]
navigatormaps_api is for the Docker Swarm Cluster.

Yes this will not map to the Internet this is fine
