### ISSUE TITLE
Get Map - application/vnd-geo+json

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#5]
When Calling the Map use content Type = application/vnd-geo+json

Server Code will change to have 2 content types

![content](https://cloud.githubusercontent.com/assets/887805/8400615/9c149a70-1def-11e5-9e32-4042d2742fe5.png)

**Comment by avmi** [comment]
Thanks for letting me know

**Comment by stuartshay** [comment]
I changed the code so now the default is applicatiion/json
For the map I want to use:  application/vnd-geo+json

You can test the output using Swagger
http://api.navigatorglass.com/swagger/ui/index#!/Maps/Maps_Get_0

If you have any questions feel free.

I would like to go over the code Thurs Night EST and on Friday give me a time that works and we can setup a  Skype chat either Text Messenger or Voice 

SkypeId: stuartshay

We can over the details and background of the project

**Comment by stuartshay** [comment]
When do you think you will have something I want to make sure I pay you for your time and everything is clear

**Comment by avmi** [comment]
Morning Shay,

Sorry, been away.
I'm about to pull an update to your repo shortly.

Available during a Friday and over weekend for your input.

Thanks,
Andrey

**Comment by stuartshay** [comment]
Do you have something or was the work never started 
I can chat right now to go over

**Comment by avmi** [comment]
Hello,

Sorry, I'm away due to personal reasons at a moment, answering from phone
and hope that github will post this into thread. I'll create pull request
with all changes by 3-4 hrs

Thanks,
Andrey

**Comment by stuartshay** [comment]
Andrey

NP I understand, it is Summer so not a issue I understand 100% 

Just want to make sure you are interested

We can go over once you check in

**Comment by avmi** [comment]
Thanks. Surely interested. Just got a mess with schedule last couple days.
Apologies. Will be online pretty soon and commit a pull request
