### ISSUE TITLE
Attraction Details DIV

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#7]
Add the Attraction Details DIV as in Mockup
http://informationcart.com/Maps/GoogleMap.html

- Just Display Title (Other Properties will be added to API)

![attractiondiv](https://cloud.githubusercontent.com/assets/887805/8664314/88ef5c18-29a3-11e5-9614-81f65cab2f0a.png)

**Comment by xibbit** [comment]
Attraction details div added. Theres is an image in the div which is same as in the list on right sidebar

![attraction details](https://cloud.githubusercontent.com/assets/674794/8714715/deea64ca-2b95-11e5-90c2-9de7659487db.png)

**Comment by stuartshay** [comment]
This is fine for now
The Photo is not the right scale, this needs to be added on the Server Side to the output which i will do
