### ISSUE TITLE
Over Lay - Green-Wood Sector

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorMaps#9]
Display Overlay - JSON May Require Reformatting 

Get Feature Collection 

<pre>
 {
    "id": "557d4ffff5094cd685a3721b",
    "name": "Green-Wood Sector"
  },
</pre>

![swagger](https://cloud.githubusercontent.com/assets/887805/8760515/87fb7cb6-2cef-11e5-8836-2f07adc39176.png)

Center Point - Greenwood Over  Lay
40.652976, -73.990840

![image](https://cloud.githubusercontent.com/assets/887805/8760565/9f5d120e-2cf2-11e5-8270-81fdffe5552d.png)

Other Layer Data Sets to be used
https://data.cityofnewyork.us/City-Government/Parks-Properties/rjaj-zgq7
https://data.cityofnewyork.us/Transportation/Subway-Stations/arq3-7z49

**Comment by xibbit** [comment]
Code pushed to branch [feature]. It displays polygons on map without color fill and labels. There are two types of data in json
Polygons and Points. Points should be displayed as markers?

**Comment by stuartshay** [comment]
Gaurav:

 

I don’t see this, Not Sure you pushed to either branch. 

 

I need the Labels and Boundaries (The Grid Lines). Not sure the color is necessary.

 

Once I see this I will have a better idea of what needs to be done, I am working on the code for the photos as you can see the Photo is not scaled correctly.

 

I should have this soon.

 

Are you good at CSS/Design if not this not a problem I can have someone else look at the Design and CSS

 

Stuart

**Comment by xibbit** [comment]
I had pushed code to branch 'feature'.
Please check the latest commit for Polygons with labels.
I can do CSS but not good at design.

**Comment by xibbit** [comment]
Please provide details for deployment to heroku
